[JIRA-003][feature] fix closet entity to myCloset entity
jsoyun/favorite_Project pull request #12
Opened 2023-12-14 15:29 UTC by jsoyun

# PR 개요
변경사항에 대한 배경설명을 적으시오
![image](https://github.com/jsoyun/favorite_Project/assets/89512178/384a1cb2-d5f7-4cb8-bb7b-be54645acc2f)

- DB구조를 반영하고자 기존 closet entity를 myCloset entity로 수정 (builder패턴 유지하고 requestMapping을 위해 생성자 추가함)
- 컬럼값에 맞춰서 closet.html, ClosetDao 도 수정하여 Create 테스트하였습니다
- DAO에서 myCloset 컬럼중 clothes_id 값이 없을 때 setNull 처리

## 변경 유형

- [ ] 자잘한 버그 수정(기능 문제해결이 아닌 수정사항)
- [x] 새로운 기능 추가
- [ ] 주요 기능 수정(기능 문제해결 수정사항)
- [x] 문서 업데이트가 필요한 수정

# 체크리스트

- [x] 변경 내용에 대해 알고 있다.
- [ ] 변경사항 추가를 위해 테스트를 마쳤다.
- [ ] 문서에 해당 변경 사항을 적용했다.
- [x] 내 변경사항으로 인해 새로운 경고가 생성되지 않는다.
- [x] 수정 사항이 효과적이거나 기능이 작동함을 입증하는 테스트를 추가했다.
- [x] 신규 및 기존 단위 테스트가 내 변경 사항에 따라 로컬로 통과된다.
- [ ] 종속된 변경 사항이 모두 통합되어 모듈에 반영되었다.

2023-12-15 06:17 UTC, torreswoo requested changes
전반적으로 myCloset이라는 네이밍을 사용하셨는데. 굉장히 이상해 보이네요. UserCloset 이라는 의미죠?

2023-12-15 06:17 UTC, torreswoo commented on project/src/main/java/com/favorite/project/controller/api/ClosetController.java
> -    public ResponseEntity<String> addCloset(@RequestBody Closet closet){
response로 JSON형태로 해줘야합니다. String을 하지말고 XXXResponse로 클래스명으로 생성후에 필요한 값들을 json으로 반환하셔야합니다.

2023-12-15 06:17 UTC, torreswoo commented on project/src/main/java/com/favorite/project/controller/api/ClosetController.java
> -    public ResponseEntity<String> addCloset(@RequestBody Closet closet){
`myCloset` 이라는 클래스명은... 실수로 하신거라고 생각하겠습니다... ClosetRequest등으로 해야겠죠?

2023-12-15 06:19 UTC, torreswoo commented on project/src/main/java/com/favorite/project/entity/myCloset.java
> +
indentation을 많이 틀리셨는데 기본적인 부분이랍니다. 이런게 틀리면 큰마이너스입니다.

2023-12-15 06:19 UTC, torreswoo commented on project/src/main/java/com/favorite/project/entity/myCloset.java
> +
이부분을 이제 `@Builder`를 사용해서 제거하세요
https://velog.io/@park2348190/Lombok-Builder%EC%9D%98-%EB%8F%99%EC%9E%91-%EC%9B%90%EB%A6%AC

2023-12-16 08:47 UTC, jsoyun commented
> 전반적으로 myCloset이라는 네이밍을 사용하셨는데. 굉장히 이상해 보이네요. UserCloset 이라는 의미죠?

네 사용자의 옷장이 맞습니다!

2023-12-16 08:48 UTC, jsoyun commented on project/src/main/java/com/favorite/project/controller/api/ClosetController.java
> -    public ResponseEntity<String> addCloset(@RequestBody Closet closet){
> `myCloset` 이라는 클래스명은... 실수로 하신거라고 생각하겠습니다... ClosetRequest등으로 해야겠죠?

넵 DB쪽 수정이 마무리가 안돼서 아직 컨트롤러에 필요한 dto를 만들지 않았기에 기존 코드 그대로 냅뒀습니다!

2023-12-17 08:07 UTC, torreswoo commented on project/src/main/java/com/favorite/project/controller/api/ClosetController.java
> -    public ResponseEntity<String> addCloset(@RequestBody Closet closet){
ClosetRequest로 변경해주세요!

2023-12-18 10:14 UTC, merged